### PR TITLE
Translations update from ioBroker Translation System

### PR DESCRIPTION
**Pull request by ioBrokerTranslator**
Translations update from [ioBroker Translation System](https://weblate.iobroker.net) for [ioBroker Adapters/bluesound](https://weblate.iobroker.net/projects/adapters/bluesound/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Uwe1958** [comment]
@mcm1957
What can I do to get this pull request done. 

I'm kind of stucked. The merging is blocked. I see many unverified commits (from Weblate).

How can I solve this situation?

**Comment by mcm1957** [comment]
Dependabot creatrs a PR. You nust merge it. I do knor know why your repobseems tobreuure signing a PR. Guess this is an option you decided tovswitch on.

Weblate does not sign PRs nor have I ever seen someone else signkbg PRs.

So either you can merge the PR or you should disable this restriction.

**Comment by mcm1957** [comment]
@apollon77
Any more info in regard to thus?

**Comment by Apollon77** [comment]
@Uwe1958 seems you required all commits to be signed ... Weblate can not provide that ... so maybe turn off this limitation for short and merge?

**Comment by mcm1957** [comment]
see - https://docs.github.com/de/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-signed-commits

I would suggest to disable signed commits as you will have to check any PR anyway. And I do not know any other iobroker repository using this enforcement.

**Pull request merged**
